Eremina_Mariia_14/WebApplication/ViewModels/RewardViewModel.cs
using Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication.ViewModels
{
    public class RewardViewModel
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Checked { get; set; }

        public static RewardViewModel GetViewModel(Reward reward, List<Reward> userRewards)
        {
            RewardViewModel newReward = new RewardViewModel();
            newReward.ID = reward.ID;
            newReward.Title = reward.Title;
            newReward.Description = reward.Description;
            newReward.Checked = false;

            if (!(userRewards is null))
            {
                foreach (Reward rew in userRewards)
                {
                    if (rew.ID == newReward.ID)
                    {
                        newReward.Checked = true;
                    }
                }
            }
            return newReward;
        }

        public static Reward ToReward(RewardViewModel rewardModel)
        {
            
            Reward reward = new Reward();
            reward.ID = rewardModel.ID;
            reward.Title = rewardModel.Title;
            reward.Description = rewardModel.Description;
            return reward;
        }
    }

}

Eremina_Mariia_14/WebApplication/ViewModels/UserViewModel.cs
using Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication.ViewModels
{
    public class UserViewModel
    {

        public UserViewModel()
        {

        }

        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime Birthdate { get; set; }
        public List<RewardViewModel> AllRewards { get; set; }


        public UserViewModel(User one, List<Reward> rewards)
        {
            ID = one.ID;
            FirstName = one.FirstName;
            LastName = one.LastName;
            Birthdate = one.Birthdate;
            AllRewards = new List<RewardViewModel>();

            foreach (Reward reward in rewards)
            {
                RewardViewModel rewardModel = RewardViewModel.GetViewModel(reward, one.reward);
                AllRewards.Add(rewardModel);
            }
        }

        public User ToUser()
        {
            User user = new User();
            user.ID = ID;
            user.FirstName = FirstName;
            user.LastName = LastName;
            user.Birthdate = Birthdate;
            user.reward = ToRewards();
            return user;
        }

        public List<Reward> ToRewards()
        {
            List<Reward> resultRewards = new List<Reward>();
            foreach (RewardViewModel rewardModel in AllRewards)
            {
                if (rewardModel.Checked)
                {
                    resultRewards.Add(RewardViewModel.ToReward(rewardModel));
                }
            }
            return resultRewards;
        }
    }
}

Eremina_Mariia_14/WebApplication/Controllers/RewardController.cs
using LogicLayer;
using Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class RewardController : Controller
    {
        public Logic logic { get; set; }

        public RewardController ()
        {
            logic = new Logic();
        }
        // GET: Reward
        public ActionResult Index()
        {
            
            var rewards = logic.GetRewards();
            return View(rewards);
            //return View();
        }

        public ActionResult Edit(int ID)
        {
            Reward reward = logic.GetRewardById(ID);
            return View(reward);
        }

        public ActionResult Delete(int ID)
        {
            Reward reward = logic.GetRewardById(ID);
            if (reward != null)
            {
                logic.RemoveReward(reward);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Add()
        {
            Reward reward = new Reward();
            return View("Edit", reward);
        }

        public ActionResult Save (Reward editReward)
        {
            if (editReward.Title != default(string))
            {
                if (editReward.ID == default(int))
                {
                        logic.AddReward(editReward);
                }
                else
                {
                    Reward reward = logic.GetRewardById(editReward.ID);
                    reward.Title = editReward.Title;
                    reward.Description = editReward.Description;
                    logic.EditReward(reward);
                }

                return RedirectToAction("Index");
            }
            else return RedirectToAction("Message");
        }

        public ActionResult Message()
        {
            return View();
        }

    }
}

Eremina_Mariia_14/WebApplication/Controllers/UserController.cs
using LogicLayer;
using Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class UserController : Controller
    {
        // GET: User

        public Logic logic { get; set; }

        public UserController()
        {
            logic = new Logic();
        }

        public ActionResult Index()
        {
            logic = new Logic();
            var users = logic.GetUsers();
            return View(users);
        }

        public ActionResult Edit(int ID)
        {
            User user = logic.GetUserById(ID);
            List<Reward> allRewards = logic.GetRewards();
            UserViewModel UVM = new UserViewModel(user, allRewards);
            return View(UVM);
        }


        public ActionResult Delete(int ID)
        {
            User user = logic.GetUserById(ID);
            if (user != null)
            {
                logic.RemoveUser(user);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Add()
        {
            User user = new User();
            List<Reward> allRewards = logic.GetRewards();
            UserViewModel UVM = new UserViewModel(user, allRewards);
            return View("Edit", UVM);
        }

        public ActionResult Save(UserViewModel UVM)
        {
            User editUser = UVM.ToUser();
            if (editUser.FirstName != default(string) && editUser.LastName != default(string) && editUser.Birthdate != default(DateTime))
            {
                if (editUser.ID == default(int))
                {
                        logic.AddUser(editUser);
                }
                else
                {
                    User user = logic.GetUserById(editUser.ID);
                    user.FirstName = editUser.FirstName;
                    user.LastName = editUser.LastName;
                    user.Birthdate = editUser.Birthdate;
                    if (editUser.reward != null)
                    {
                        user.reward = editUser.reward;
                        user.RefreshRewards(user.reward);
                    }
                    logic.EditUser(editUser);
                }

                return RedirectToAction("Index");
            }
            else return RedirectToAction("Message");
        }

        public ActionResult Message()
        {
            return View();
        }

    }
}

Eremina_Mariia_14/WebApplication/Views/Reward/Edit.cshtml
@model Shared.Reward
@{

    Layout = "~/Views/Shared/_Layout.cshtml";

    if (Model.Title == default(string))
    {
        ViewBag.Title = "Add";
    }
    else
    {
        ViewBag.Title = "Edit";
    }

    Shared.Reward thisReward = Model;
}

@{
    if (Model.ID == default(int))
    {
        <h3>Add Reward</h3>
    }
    else
    {
        <h3>Edit Reward</h3>
    }
}

<form action="Save" method="post">
    <input name="Id" style="display: none;" value="@thisReward.ID" />
    <div class="form-group">
        <label for="Title">Title</label>
        <input name="Title" type="text" class="form-control" id="Title" value="@thisReward.Title" />
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <input name="Description" type="text" class="form-control" id="Description" value="@thisReward.Description" />
    </div>

    <div class="form-group">
        <button type="submit" class="btn">Save</button>
        @Html.ActionLink("Cancel", "Index", "User")
    </div>
</form>

Eremina_Mariia_14/WebApplication/Views/Reward/Index.cshtml
@model List<Shared.Reward>
@{
    ViewBag.Title = "Rewards";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<table class="table">
    <caption><h2>Rewards</h2></caption>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th> </th>
            <th> </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var reward in Model)
        {
        <tr>
            <td>@reward.Title</td>
            <td>@reward.Description</td>
            <td><a href="Reward/Edit?id=@reward.ID">Edit</a></td>
            <td><a href="Reward/Delete?id=@reward.ID">Delete</a></td>
        </tr>
        }
    </tbody>
</table>

<h4 class="btn"><a href="Reward/Add">Add new reward</a></h4>

Eremina_Mariia_14/WebApplication/Views/Shared/Message.cshtml
@{
    ViewBag.Title = "Message";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Message</h2>
<p> Something was wrong. Changes wasn't saved.</p>
@Html.ActionLink("Cancel", "Index", "User")

Eremina_Mariia_14/WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                    <li>@Html.ActionLink("Rewards", "Index", "Reward")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Eremina_Mariia_14/WebApplication/Views/User/Edit.cshtml
@model WebApplication.ViewModels.UserViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    if (Model.FirstName == default(string))
    {
        ViewBag.Title = "Add";
    }
    else
    {
        ViewBag.Title = "Edit";
    }

    WebApplication.ViewModels.UserViewModel UVM = Model;
    Shared.User thisUser = UVM.ToUser();
    List<WebApplication.ViewModels.RewardViewModel> AllRewards = UVM.AllRewards;

}

@{
    if (Model.ID == default(int))
    {
        <h3>Add User</h3>
    }
    else
    {
        <h3>Edit User</h3>
    }
}

<form action="Save" method="post">
    <input name="ID" style="display: none;" value="@thisUser.ID" />
    <div class="form-group">
        <label for="FirstName">First Name</label>
        <input name="FirstName" type="text" class="form-control" id="FirstName" value="@thisUser.FirstName" />
    </div>
    <div class="form-group">
        <label for="LastName">Last Name</label>
        <input name="LastName" type="text" class="form-control" id="LastName" value="@thisUser.LastName" />
    </div>
    <div class="form-group">
        <label for="Birthdate">Birthdate</label>
        <input name="Birthdate" type="date" class="form-control" id="Birthdate" value="@thisUser.Birthdate.ToString("yyyy-MM-dd")" />
    </div>

    <div class="form-group">
        <label> Rewards </label>
        <br />
        @{

        for (int i = 0; i < AllRewards.Count; i++)

        {
            <p>@AllRewards[i].Title</p>
            @Html.EditorFor(model => model.AllRewards[i].Checked)
            @Html.HiddenFor(model => model.AllRewards[i].ID)
    }

        }


        <br />
    </div>


    @*@{

            for (int i = 0; i < allRewards.Count; i++)
            {
        <p>@allRewards[i].Title</p>

                bool exists = false;
                foreach (Shared.Reward reward in thisUser.reward)
                {
                    if (reward.ID == allRewards[i].ID)
                    {
                        exists = true;
                    }
                }

                if (exists)
                {
                <input name="reward" type="checkbox" class="form-control" id="reward" value="@allRewards[i]" checked />
                }
                else
                {
                <input name="reward" type="checkbox" class="form-control" id="reward" value="@allRewards[i]" />
                    }

                }
            }*@

    <div class="form-group">
        <button type="submit" class="btn">Save</button>
        @Html.ActionLink("Cancel", "Index", "User")
        @*<div class="btn"><a href="User/Index">Cancel</a></div>*@
    </div>
</form>

Eremina_Mariia_14/WebApplication/Views/User/Index.cshtml
@model List<Shared.User>
@{
    ViewBag.Title = "Users";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<table class="table">
    <caption><h2>Users</h2></caption>
    <thead>
        <tr>
            <th>Name</th>
            <th>Lastname</th>
            <th>Birthdate</th>
            <th>Age</th>
            <th>Rewards</th>
            <th> </th>
            <th> </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var user in Model)
        {
        <tr>
            <td>@user.FirstName</td>
            <td>@user.LastName</td>
            <td>@user.Birthdate.ToShortDateString()</td>
            <td>@user.Age</td>
            <td>@user.Rewards</td>
            <td><a href="User/Edit?id=@user.ID">Edit</a></td>
            <td><a href="User/Delete?id=@user.ID">Delete</a></td>
        </tr>
        }
    </tbody>

</table>

<h4 class="btn"><a href="User/Add">Add new user</a></h4>